/**
 * User preferences: language + appearance theme (localStorage).
 * UI chrome translations for many languages; product/admin copy stays as authored.
 */
const THEME_KEY = "subsaverph_theme";
const LANG_KEY = "subsaverph_lang";

export const THEMES = [
  { id: "dark", labelKey: "theme_dark" },
  { id: "light", labelKey: "theme_light" },
  { id: "system", labelKey: "theme_system" },
];

/** All selectable languages (id used in <html lang> + storage) */
export const LANGUAGES = [
  { id: "en", label: "English", native: "English", dir: "ltr" },
  { id: "fil", label: "Filipino", native: "Filipino", dir: "ltr" },
  { id: "ceb", label: "Cebuano", native: "Bisaya / Cebuano", dir: "ltr" },
  { id: "es", label: "Spanish", native: "Español", dir: "ltr" },
  { id: "zh", label: "Chinese (Simplified)", native: "简体中文", dir: "ltr" },
  { id: "zh-TW", label: "Chinese (Traditional)", native: "繁體中文", dir: "ltr" },
  { id: "ja", label: "Japanese", native: "日本語", dir: "ltr" },
  { id: "ko", label: "Korean", native: "한국어", dir: "ltr" },
  { id: "vi", label: "Vietnamese", native: "Tiếng Việt", dir: "ltr" },
  { id: "th", label: "Thai", native: "ไทย", dir: "ltr" },
  { id: "id", label: "Indonesian", native: "Bahasa Indonesia", dir: "ltr" },
  { id: "ms", label: "Malay", native: "Bahasa Melayu", dir: "ltr" },
  { id: "hi", label: "Hindi", native: "हिन्दी", dir: "ltr" },
  { id: "ar", label: "Arabic", native: "العربية", dir: "rtl" },
  { id: "fr", label: "French", native: "Français", dir: "ltr" },
  { id: "de", label: "German", native: "Deutsch", dir: "ltr" },
  { id: "pt", label: "Portuguese", native: "Português", dir: "ltr" },
  { id: "pt-BR", label: "Portuguese (Brazil)", native: "Português (Brasil)", dir: "ltr" },
  { id: "ru", label: "Russian", native: "Русский", dir: "ltr" },
  { id: "it", label: "Italian", native: "Italiano", dir: "ltr" },
  { id: "nl", label: "Dutch", native: "Nederlands", dir: "ltr" },
  { id: "tr", label: "Turkish", native: "Türkçe", dir: "ltr" },
  { id: "pl", label: "Polish", native: "Polski", dir: "ltr" },
  { id: "uk", label: "Ukrainian", native: "Українська", dir: "ltr" },
  { id: "ro", label: "Romanian", native: "Română", dir: "ltr" },
  { id: "sv", label: "Swedish", native: "Svenska", dir: "ltr" },
  { id: "fi", label: "Finnish", native: "Suomi", dir: "ltr" },
  { id: "no", label: "Norwegian", native: "Norsk", dir: "ltr" },
  { id: "da", label: "Danish", native: "Dansk", dir: "ltr" },
  { id: "el", label: "Greek", native: "Ελληνικά", dir: "ltr" },
  { id: "he", label: "Hebrew", native: "עברית", dir: "rtl" },
  { id: "bn", label: "Bengali", native: "বাংলা", dir: "ltr" },
  { id: "ta", label: "Tamil", native: "தமிழ்", dir: "ltr" },
  { id: "ur", label: "Urdu", native: "اردو", dir: "rtl" },
  { id: "fa", label: "Persian", native: "فارسی", dir: "rtl" },
  { id: "sw", label: "Swahili", native: "Kiswahili", dir: "ltr" },
];

const LANG_IDS = new Set(LANGUAGES.map((l) => l.id));

const EN = {
  nav_home: "Home",
  nav_deals: "Deals",
  nav_search: "Search",
  nav_mission: "Mission",
  nav_checkout: "Checkout",
  nav_pay: "Pay",
  nav_cart: "Cart",
  nav_menu: "Menu",
  nav_prefs: "Settings",
  prefs_title: "Preferences",
  prefs_language: "Language",
  prefs_theme: "Appearance",
  prefs_theme_hint: "Choose light, dark, or match your device.",
  prefs_lang_hint: "UI language for menus and buttons.",
  theme_dark: "Dark",
  theme_light: "Light",
  theme_system: "System",
  search_placeholder: "Search SuperGrok, Netflix…",
  search_aria: "Search products",
  cart_title: "Cart",
  cart_close: "Close",
  cart_subtotal: "Subtotal",
  cart_save: "You save",
  cart_total: "Total",
  cart_checkout: "Checkout",
  cart_empty: "Cart empty",
  cart_find: "Find a plan",
  footer_shop: "Shop",
  footer_company: "Company",
  footer_legal: "Legal",
  footer_about_company: "About the company",
  footer_about: "About",
  footer_terms: "Terms of Use",
  footer_privacy: "Privacy Policy",
  footer_how: "How it works",
  footer_all_deals: "All deals",
  footer_contact: "Support",
  cta_search: "Open search",
  cta_browse: "Browse deals",
  eyebrow_platforms: "Platforms",
  eyebrow_catalog: "Catalog",
  view_all: "View all",
  page_deals: "All deals",
  page_search: "Search",
  page_results: "Results",
  page_how: "How it works",
  toast_theme: "Theme updated",
  toast_lang: "Language updated",
  toast_pay: "Pay in",
  meta_plans: "Active plans",
  meta_platforms: "Platforms",
  meta_currencies: "Currencies",
  currency_search: "Search currency (PHP, USD, euro…)",
  // Homepage / content
  hero_eyebrow: "SubSaverPH · Subscription access",
  hero_title: "Premium\nplans.\nLower\ncost.",
  hero_lead: "Prepaid access to premium subscriptions at outlet rates. Checkout in any currency.",
  platforms_title: "Select a service",
  catalog_title: "Highest savings",
  mission_title: "Stack subscriptions without stacking full price",
  mission_text: "AI, Design, Video, and Streaming plans at outlet rates.",
  strip1: "Secure checkout",
  strip2: "Searchable FX pay",
  strip3: "Instant digital codes",
  strip4: "Demo storefront",
  why_prefix: "Why",
  search_results_title: "Results",
  search_only_match: "Only products that match",
  search_are_shown: "are shown.",
  products_found: "products found",
  product_found: "product found",
  clear_search: "Clear search",
  no_products_matched: "No products matched",
  try_brands: "Try SuperGrok, Netflix, or Canva.",
  search_product_ph: "Search a product name…",
  // Product UI
  details: "Details",
  add: "Add",
  add_to_cart: "Add to cart",
  buy_now: "Buy now",
  sold_out: "SOLD OUT",
  in_stock: "In stock",
  only_left: "Only {n} left",
  n_in_stock: "{n} in stock",
  per_7_days: " / 7 days",
  per_month: " / month",
  plan_not_found: "Plan not found",
  back: "Back",
  all_deals: "All deals",
  versus_retail: "Versus retail",
  no_codes_left: "No codes left in stock",
  base_price_php: "Base price in PHP · shows exact PHP amount when currency is PHP",
  yearly_deal: "Yearly at deal rate",
  yearly_retail: "Yearly at retail",
  reviews: "reviews",
  retail: "retail",
  save: "Save",
  pick_another: "This plan has no codes left. Check back later or pick another product.",
  // How it works
  protocol: "Protocol",
  how_step1_t: "Search",
  how_step1_p: "Use the home search bar to find plans by category — AI, Design, Video, or Streaming.",
  how_step2_t: "Currency",
  how_step2_p: "Open Pay → search any currency (PHP, USD, EUR…). Prices convert when you change currency.",
  how_step3_t: "Checkout",
  how_step3_p: "Complete checkout with your preferred payment method. Codes appear on confirmation.",
  how_step4_t: "Redeem",
  how_step4_p: "Apply codes on the official service. Keep the order ID.",
  demo_notice: "Demo notice",
  demo_notice_p: "SubSaverPH offers prepaid digital access across AI, Design, Video, and Streaming. Independent storefront — not affiliated with any brand listed in the catalog.",
  // Footer content
  footer_blurb: "Discounted prepaid plans across AI, Design, Video, and Streaming. Searchable multi-currency payment.",
  footer_company_blurb: "SubSaverPH is an online storefront for discounted prepaid digital subscriptions in the Philippines — covering AI, Design, Video, and Streaming categories. We focus on clear pricing, multi-currency checkout, and instant digital delivery.",
  footer_service_area: "Philippines (online)",
  footer_business_type: "Digital goods / prepaid access codes",
  footer_disclaimer: "SubSaverPH is an independent storefront and is not affiliated with, endorsed by, or sponsored by the brands behind products in our AI, Design, Video, or Streaming categories. Product names are trademarks of their respective owners.",
  footer_copyright: "SubSaverPH. All rights reserved.",
  brand_meta: "Brand",
  service_area_meta: "Service area",
  website_meta: "Website",
  support_meta: "Support",
  business_type_meta: "Business type",
  // Legal
  about_title: "About SubSaverPH",
  about_updated: "July 16, 2026",
  about_body: "Who we are\n\nSubSaverPH is an online storefront based in the Philippines that offers discounted prepaid digital subscriptions and access codes across four categories: AI, Design, Video, and Streaming.\n\nOur goal is simple: help customers stack the plans they need without paying full retail every month, with clear PHP-first pricing and multi-currency checkout.\n\nWhat we sell\n\n• Prepaid subscription access (digital delivery)\n• Outlet-style pricing on selected plan lengths\n• Instant or email delivery of codes / redeem instructions after successful payment\n• Plans grouped by category — AI, Design, Video, and Streaming\n\nContact\n\nFor order help, refunds, or partnership questions, email support@subsaverph.com and include your order ID when possible.",
  terms_title: "Terms of Use",
  terms_updated: "July 16, 2026",
  terms_body: "These Terms of Use govern your access to and use of the SubSaverPH website. By using the Site, you agree to these Terms.\n\n1. Eligibility\n\nYou must be at least 18 years old and able to form a binding contract to place an order.\n\n2. Products & digital delivery\n\nSubSaverPH sells prepaid digital subscriptions, access codes, or redeem instructions. Products are delivered digitally after payment is confirmed.\n\n3. Pricing & currency\n\nPrices may be shown in PHP or converted currencies. The amount charged is confirmed at checkout.\n\n4. Refunds\n\nDigital goods have limited refunds. Contact support with your order ID if a code is defective or not delivered.\n\n5. Contact\n\nQuestions: support@subsaverph.com",
  privacy_title: "Privacy Policy",
  privacy_updated: "July 16, 2026",
  privacy_body: "This Privacy Policy explains how SubSaverPH collects, uses, and protects information when you use our website.\n\n1. Information we collect\n\nOrder information (email, cart, payment status), technical data (IP, browser), and messages you send to support.\n\n2. How we use information\n\nTo process orders, deliver codes, prevent fraud, improve the site, and comply with law.\n\n3. Sharing\n\nWe share data only with payment processors, hosting providers, and when required by law. We do not sell your personal information.\n\n4. Contact\n\nPrivacy questions: support@subsaverph.com",
  company: "Company",
  legal: "Legal",
  last_updated: "Last updated",
  back_to_home: "Back to home",
  // Rates / cart extras
  live_fx: "Live FX",
  cached_fx: "Cached FX",
  offline_fx: "Offline FX",
  currencies_word: "currencies",
  pay_in: "pay in",
  translating: "Translating page…",
  sort_label: "Sort",
  filter_all: "All",
};

/** Partial overrides per language; missing keys fall back to English */
const OVERRIDES = {
  fil: {
    nav_deals: "Mga deal",
    nav_search: "Maghanap",
    nav_mission: "Misyon",
    nav_pay: "Bayad",
    nav_prefs: "Mga setting",
    prefs_title: "Mga kagustuhan",
    prefs_language: "Wika",
    prefs_theme: "Hitsura",
    prefs_theme_hint: "Pumili ng light, dark, o ayon sa device.",
    prefs_lang_hint: "Wika ng menu at mga button.",
    theme_dark: "Madilim",
    theme_light: "Maliwanag",
    search_placeholder: "Maghanap ng SuperGrok, Netflix…",
    search_aria: "Maghanap ng produkto",
    cart_close: "Isara",
    cart_save: "Natipid mo",
    cart_total: "Kabuuan",
    cart_empty: "Walang laman ang cart",
    cart_find: "Maghanap ng plan",
    footer_shop: "Tindahan",
    footer_company: "Kumpanya",
    footer_about_company: "Tungkol sa kumpanya",
    footer_about: "Tungkol",
    footer_terms: "Mga tuntunin",
    footer_how: "Paano gumagana",
    footer_all_deals: "Lahat ng deal",
    footer_contact: "Makipag-ugnayan",
    cta_search: "Buksan ang search",
    cta_browse: "Tingnan ang deals",
    eyebrow_platforms: "Mga platform",
    eyebrow_catalog: "Katalogo",
    view_all: "Tingnan lahat",
    page_deals: "Lahat ng deal",
    page_search: "Maghanap",
    page_results: "Mga resulta",
    page_how: "Paano gumagana",
    toast_theme: "Na-update ang theme",
    toast_lang: "Na-update ang wika",
    toast_pay: "Magbayad sa",
    meta_plans: "Mga plan",
    currency_search: "Maghanap ng currency (PHP, USD…)",
  },
  ceb: {
    nav_deals: "Mga deal",
    nav_search: "Pangita",
    nav_mission: "Misyon",
    nav_pay: "Bayad",
    nav_prefs: "Mga setting",
    prefs_title: "Mga preperensya",
    prefs_language: "Pinulongan",
    prefs_theme: "Hitsura",
    theme_dark: "Ngitngit",
    theme_light: "Hayag",
    cart_close: "Sirado",
    cart_save: "Imong natipid",
    cart_total: "Kinatibuk-an",
    cart_empty: "Walay sulod ang cart",
    footer_shop: "Tindahan",
    footer_company: "Kompanya",
    footer_about: "Mahitungod",
    footer_how: "Unsaon kini",
    cta_browse: "Tan-awa ang deals",
    view_all: "Tan-awa tanan",
    toast_lang: "Na-update ang pinulongan",
    toast_pay: "Bayad sa",
  },
  es: {
    nav_home: "Inicio",
    nav_deals: "Ofertas",
    nav_search: "Buscar",
    nav_mission: "Misión",
    nav_checkout: "Pagar",
    nav_pay: "Pagar",
    nav_cart: "Carrito",
    nav_menu: "Menú",
    nav_prefs: "Ajustes",
    prefs_title: "Preferencias",
    prefs_language: "Idioma",
    prefs_theme: "Apariencia",
    prefs_theme_hint: "Elige claro, oscuro o el del dispositivo.",
    prefs_lang_hint: "Idioma de menús y botones.",
    theme_dark: "Oscuro",
    theme_light: "Claro",
    theme_system: "Sistema",
    search_placeholder: "Buscar SuperGrok, Netflix…",
    search_aria: "Buscar productos",
    cart_title: "Carrito",
    cart_close: "Cerrar",
    cart_subtotal: "Subtotal",
    cart_save: "Ahorras",
    cart_total: "Total",
    cart_checkout: "Pagar",
    cart_empty: "Carrito vacío",
    cart_find: "Buscar un plan",
    footer_shop: "Tienda",
    footer_company: "Empresa",
    footer_legal: "Legal",
    footer_about_company: "Sobre la empresa",
    footer_about: "Acerca de",
    footer_terms: "Términos de uso",
    footer_privacy: "Privacidad",
    footer_how: "Cómo funciona",
    footer_all_deals: "Todas las ofertas",
    footer_contact: "Contactar soporte",
    cta_search: "Abrir búsqueda",
    cta_browse: "Ver ofertas",
    eyebrow_platforms: "Plataformas",
    eyebrow_catalog: "Catálogo",
    view_all: "Ver todo",
    page_deals: "Todas las ofertas",
    page_search: "Buscar",
    page_results: "Resultados",
    page_how: "Cómo funciona",
    toast_theme: "Tema actualizado",
    toast_lang: "Idioma actualizado",
    toast_pay: "Pagar en",
    meta_plans: "Planes activos",
    meta_platforms: "Plataformas",
    meta_currencies: "Monedas",
    currency_search: "Buscar moneda (PHP, USD, euro…)",
  },
  zh: {
    nav_home: "首页",
    nav_deals: "优惠",
    nav_search: "搜索",
    nav_mission: "使命",
    nav_checkout: "结账",
    nav_pay: "支付",
    nav_cart: "购物车",
    nav_menu: "菜单",
    nav_prefs: "设置",
    prefs_title: "偏好设置",
    prefs_language: "语言",
    prefs_theme: "外观",
    prefs_theme_hint: "选择浅色、深色或跟随系统。",
    prefs_lang_hint: "菜单和按钮的界面语言。",
    theme_dark: "深色",
    theme_light: "浅色",
    theme_system: "系统",
    search_placeholder: "搜索 SuperGrok、Netflix…",
    search_aria: "搜索产品",
    cart_title: "购物车",
    cart_close: "关闭",
    cart_subtotal: "小计",
    cart_save: "已省",
    cart_total: "合计",
    cart_checkout: "结账",
    cart_empty: "购物车为空",
    cart_find: "查找套餐",
    footer_shop: "商店",
    footer_company: "公司",
    footer_legal: "法律",
    footer_about_company: "关于公司",
    footer_about: "关于",
    footer_terms: "使用条款",
    footer_privacy: "隐私政策",
    footer_how: "使用方法",
    footer_all_deals: "全部优惠",
    footer_contact: "联系客服",
    cta_search: "打开搜索",
    cta_browse: "浏览优惠",
    eyebrow_platforms: "平台",
    eyebrow_catalog: "目录",
    view_all: "查看全部",
    page_deals: "全部优惠",
    page_search: "搜索",
    page_results: "结果",
    page_how: "使用方法",
    toast_theme: "主题已更新",
    toast_lang: "语言已更新",
    toast_pay: "支付货币",
    meta_plans: "在售套餐",
    meta_platforms: "平台",
    meta_currencies: "货币",
    currency_search: "搜索货币（PHP、USD…）",
  },
  "zh-TW": {
    nav_home: "首頁",
    nav_deals: "優惠",
    nav_search: "搜尋",
    nav_mission: "使命",
    nav_checkout: "結帳",
    nav_pay: "支付",
    nav_cart: "購物車",
    nav_menu: "選單",
    nav_prefs: "設定",
    prefs_title: "偏好設定",
    prefs_language: "語言",
    prefs_theme: "外觀",
    prefs_theme_hint: "選擇淺色、深色或跟隨系統。",
    prefs_lang_hint: "選單與按鈕的介面語言。",
    theme_dark: "深色",
    theme_light: "淺色",
    theme_system: "系統",
    search_placeholder: "搜尋 SuperGrok、Netflix…",
    search_aria: "搜尋產品",
    cart_title: "購物車",
    cart_close: "關閉",
    cart_subtotal: "小計",
    cart_save: "已省",
    cart_total: "合計",
    cart_checkout: "結帳",
    cart_empty: "購物車是空的",
    cart_find: "尋找方案",
    footer_shop: "商店",
    footer_company: "公司",
    footer_legal: "法律",
    footer_about_company: "關於公司",
    footer_about: "關於",
    footer_terms: "使用條款",
    footer_privacy: "隱私權政策",
    footer_how: "使用方式",
    footer_all_deals: "全部優惠",
    footer_contact: "聯絡客服",
    cta_search: "開啟搜尋",
    cta_browse: "瀏覽優惠",
    eyebrow_platforms: "平台",
    eyebrow_catalog: "目錄",
    view_all: "查看全部",
    page_deals: "全部優惠",
    page_search: "搜尋",
    page_results: "結果",
    page_how: "使用方式",
    toast_theme: "主題已更新",
    toast_lang: "語言已更新",
    toast_pay: "支付貨幣",
    meta_plans: "進行中方案",
    meta_platforms: "平台",
    meta_currencies: "貨幣",
    currency_search: "搜尋貨幣（PHP、USD…）",
  },
  ja: {
    nav_home: "ホーム",
    nav_deals: "お得情報",
    nav_search: "検索",
    nav_mission: "ミッション",
    nav_checkout: "チェックアウト",
    nav_pay: "支払い",
    nav_cart: "カート",
    nav_menu: "メニュー",
    nav_prefs: "設定",
    prefs_title: "環境設定",
    prefs_language: "言語",
    prefs_theme: "外観",
    prefs_theme_hint: "ライト・ダーク・端末に合わせるを選択。",
    prefs_lang_hint: "メニューとボタンの表示言語。",
    theme_dark: "ダーク",
    theme_light: "ライト",
    theme_system: "システム",
    search_placeholder: "SuperGrok、Netflix を検索…",
    search_aria: "商品を検索",
    cart_title: "カート",
    cart_close: "閉じる",
    cart_subtotal: "小計",
    cart_save: "お得額",
    cart_total: "合計",
    cart_checkout: "購入手続き",
    cart_empty: "カートは空です",
    cart_find: "プランを探す",
    footer_shop: "ショップ",
    footer_company: "会社情報",
    footer_legal: "法的情報",
    footer_about_company: "会社について",
    footer_about: "概要",
    footer_terms: "利用規約",
    footer_privacy: "プライバシー",
    footer_how: "ご利用方法",
    footer_all_deals: "すべてのお得情報",
    footer_contact: "サポートに連絡",
    cta_search: "検索を開く",
    cta_browse: "お得情報を見る",
    eyebrow_platforms: "プラットフォーム",
    eyebrow_catalog: "カタログ",
    view_all: "すべて見る",
    page_deals: "すべてのお得情報",
    page_search: "検索",
    page_results: "結果",
    page_how: "ご利用方法",
    toast_theme: "テーマを更新しました",
    toast_lang: "言語を更新しました",
    toast_pay: "支払通貨",
    meta_plans: "販売中プラン",
    meta_platforms: "プラットフォーム",
    meta_currencies: "通貨",
    currency_search: "通貨を検索（PHP、USD…）",
  },
  ko: {
    nav_home: "홈",
    nav_deals: "특가",
    nav_search: "검색",
    nav_mission: "미션",
    nav_checkout: "결제",
    nav_pay: "결제",
    nav_cart: "장바구니",
    nav_menu: "메뉴",
    nav_prefs: "설정",
    prefs_title: "환경설정",
    prefs_language: "언어",
    prefs_theme: "테마",
    prefs_theme_hint: "라이트, 다크 또는 기기 설정에 맞춥니다.",
    prefs_lang_hint: "메뉴와 버튼 UI 언어입니다.",
    theme_dark: "다크",
    theme_light: "라이트",
    theme_system: "시스템",
    search_placeholder: "SuperGrok, Netflix 검색…",
    search_aria: "상품 검색",
    cart_title: "장바구니",
    cart_close: "닫기",
    cart_subtotal: "소계",
    cart_save: "절약 금액",
    cart_total: "합계",
    cart_checkout: "결제하기",
    cart_empty: "장바구니가 비어 있습니다",
    cart_find: "요금제 찾기",
    footer_shop: "쇼핑",
    footer_company: "회사",
    footer_legal: "법적 고지",
    footer_about_company: "회사 소개",
    footer_about: "소개",
    footer_terms: "이용약관",
    footer_privacy: "개인정보 처리방침",
    footer_how: "이용 방법",
    footer_all_deals: "모든 특가",
    footer_contact: "고객지원 문의",
    cta_search: "검색 열기",
    cta_browse: "특가 보기",
    eyebrow_platforms: "플랫폼",
    eyebrow_catalog: "카탈로그",
    view_all: "전체 보기",
    page_deals: "모든 특가",
    page_search: "검색",
    page_results: "결과",
    page_how: "이용 방법",
    toast_theme: "테마가 업데이트되었습니다",
    toast_lang: "언어가 업데이트되었습니다",
    toast_pay: "결제 통화",
    meta_plans: "활성 요금제",
    meta_platforms: "플랫폼",
    meta_currencies: "통화",
    currency_search: "통화 검색 (PHP, USD…)",
  },
  vi: {
    nav_home: "Trang chủ",
    nav_deals: "Ưu đãi",
    nav_search: "Tìm kiếm",
    nav_mission: "Sứ mệnh",
    nav_checkout: "Thanh toán",
    nav_pay: "Thanh toán",
    nav_cart: "Giỏ hàng",
    nav_menu: "Menu",
    nav_prefs: "Cài đặt",
    prefs_title: "Tùy chọn",
    prefs_language: "Ngôn ngữ",
    prefs_theme: "Giao diện",
    theme_dark: "Tối",
    theme_light: "Sáng",
    theme_system: "Hệ thống",
    cart_close: "Đóng",
    cart_save: "Bạn tiết kiệm",
    cart_total: "Tổng",
    cart_empty: "Giỏ hàng trống",
    footer_shop: "Cửa hàng",
    footer_company: "Công ty",
    footer_about: "Giới thiệu",
    footer_terms: "Điều khoản",
    footer_privacy: "Quyền riêng tư",
    footer_how: "Cách hoạt động",
    cta_browse: "Xem ưu đãi",
    view_all: "Xem tất cả",
    toast_lang: "Đã cập nhật ngôn ngữ",
    toast_pay: "Thanh toán bằng",
  },
  th: {
    nav_home: "หน้าแรก",
    nav_deals: "ดีล",
    nav_search: "ค้นหา",
    nav_mission: "พันธกิจ",
    nav_checkout: "ชำระเงิน",
    nav_pay: "ชำระเงิน",
    nav_cart: "ตะกร้า",
    nav_menu: "เมนู",
    nav_prefs: "การตั้งค่า",
    prefs_title: "ค่ากำหนด",
    prefs_language: "ภาษา",
    prefs_theme: "ธีม",
    theme_dark: "มืด",
    theme_light: "สว่าง",
    theme_system: "ระบบ",
    cart_close: "ปิด",
    cart_save: "ประหยัด",
    cart_total: "รวม",
    cart_empty: "ตะกร้าว่าง",
    footer_shop: "ร้านค้า",
    footer_company: "บริษัท",
    footer_about: "เกี่ยวกับ",
    footer_terms: "ข้อกำหนด",
    footer_privacy: "ความเป็นส่วนตัว",
    cta_browse: "ดูดีล",
    view_all: "ดูทั้งหมด",
    toast_lang: "อัปเดตภาษาแล้ว",
    toast_pay: "ชำระเป็น",
  },
  id: {
    nav_home: "Beranda",
    nav_deals: "Penawaran",
    nav_search: "Cari",
    nav_mission: "Misi",
    nav_checkout: "Checkout",
    nav_pay: "Bayar",
    nav_cart: "Keranjang",
    nav_menu: "Menu",
    nav_prefs: "Pengaturan",
    prefs_title: "Preferensi",
    prefs_language: "Bahasa",
    prefs_theme: "Tampilan",
    theme_dark: "Gelap",
    theme_light: "Terang",
    theme_system: "Sistem",
    cart_close: "Tutup",
    cart_save: "Anda hemat",
    cart_total: "Total",
    cart_empty: "Keranjang kosong",
    footer_shop: "Toko",
    footer_company: "Perusahaan",
    footer_about: "Tentang",
    footer_terms: "Syarat penggunaan",
    footer_privacy: "Privasi",
    footer_how: "Cara kerja",
    cta_browse: "Lihat penawaran",
    view_all: "Lihat semua",
    toast_lang: "Bahasa diperbarui",
    toast_pay: "Bayar dengan",
  },
  ms: {
    nav_home: "Laman utama",
    nav_deals: "Tawaran",
    nav_search: "Cari",
    nav_mission: "Misi",
    nav_checkout: "Checkout",
    nav_pay: "Bayar",
    nav_cart: "Troli",
    nav_prefs: "Tetapan",
    prefs_title: "Keutamaan",
    prefs_language: "Bahasa",
    prefs_theme: "Penampilan",
    theme_dark: "Gelap",
    theme_light: "Cerah",
    cart_close: "Tutup",
    cart_save: "Anda jimat",
    cart_total: "Jumlah",
    cart_empty: "Troli kosong",
    footer_shop: "Kedai",
    footer_company: "Syarikat",
    footer_about: "Perihal",
    footer_terms: "Terma penggunaan",
    footer_privacy: "Privasi",
    cta_browse: "Lihat tawaran",
    view_all: "Lihat semua",
    toast_lang: "Bahasa dikemas kini",
    toast_pay: "Bayar dalam",
  },
  hi: {
    nav_home: "होम",
    nav_deals: "डील्स",
    nav_search: "खोजें",
    nav_mission: "मिशन",
    nav_checkout: "चेकआउट",
    nav_pay: "भुगतान",
    nav_cart: "कार्ट",
    nav_menu: "मेनू",
    nav_prefs: "सेटिंग्स",
    prefs_title: "प्राथमिकताएँ",
    prefs_language: "भाषा",
    prefs_theme: "दिखावट",
    theme_dark: "डार्क",
    theme_light: "लाइट",
    theme_system: "सिस्टम",
    cart_close: "बंद करें",
    cart_save: "आप बचाते हैं",
    cart_total: "कुल",
    cart_empty: "कार्ट खाली है",
    footer_shop: "दुकान",
    footer_company: "कंपनी",
    footer_about: "परिचय",
    footer_terms: "उपयोग की शर्तें",
    footer_privacy: "गोपनीयता",
    cta_browse: "डील्स देखें",
    view_all: "सभी देखें",
    toast_lang: "भाषा अपडेट हुई",
    toast_pay: "भुगतान मुद्रा",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_deals: "العروض",
    nav_search: "بحث",
    nav_mission: "المهمة",
    nav_checkout: "الدفع",
    nav_pay: "الدفع",
    nav_cart: "السلة",
    nav_menu: "القائمة",
    nav_prefs: "الإعدادات",
    prefs_title: "التفضيلات",
    prefs_language: "اللغة",
    prefs_theme: "المظهر",
    prefs_theme_hint: "اختر فاتح أو داكن أو حسب الجهاز.",
    prefs_lang_hint: "لغة القوائم والأزرار.",
    theme_dark: "داكن",
    theme_light: "فاتح",
    theme_system: "النظام",
    search_placeholder: "ابحث عن SuperGrok و Netflix…",
    search_aria: "البحث عن المنتجات",
    cart_title: "السلة",
    cart_close: "إغلاق",
    cart_subtotal: "المجموع الفرعي",
    cart_save: "توفيرك",
    cart_total: "الإجمالي",
    cart_checkout: "إتمام الشراء",
    cart_empty: "السلة فارغة",
    cart_find: "ابحث عن خطة",
    footer_shop: "المتجر",
    footer_company: "الشركة",
    footer_legal: "قانوني",
    footer_about_company: "عن الشركة",
    footer_about: "حول",
    footer_terms: "شروط الاستخدام",
    footer_privacy: "الخصوصية",
    footer_how: "كيف يعمل",
    footer_all_deals: "كل العروض",
    footer_contact: "تواصل مع الدعم",
    cta_search: "فتح البحث",
    cta_browse: "تصفح العروض",
    eyebrow_platforms: "المنصات",
    eyebrow_catalog: "الكتالوج",
    view_all: "عرض الكل",
    page_deals: "كل العروض",
    page_search: "بحث",
    page_results: "النتائج",
    page_how: "كيف يعمل",
    toast_theme: "تم تحديث المظهر",
    toast_lang: "تم تحديث اللغة",
    toast_pay: "الدفع بـ",
    meta_plans: "الخطط النشطة",
    meta_platforms: "المنصات",
    meta_currencies: "العملات",
    currency_search: "ابحث عن عملة (PHP, USD…)",
  },
  fr: {
    nav_home: "Accueil",
    nav_deals: "Offres",
    nav_search: "Recherche",
    nav_mission: "Mission",
    nav_checkout: "Paiement",
    nav_pay: "Payer",
    nav_cart: "Panier",
    nav_menu: "Menu",
    nav_prefs: "Paramètres",
    prefs_title: "Préférences",
    prefs_language: "Langue",
    prefs_theme: "Apparence",
    prefs_theme_hint: "Choisissez clair, sombre ou système.",
    prefs_lang_hint: "Langue des menus et boutons.",
    theme_dark: "Sombre",
    theme_light: "Clair",
    theme_system: "Système",
    search_placeholder: "Rechercher SuperGrok, Netflix…",
    search_aria: "Rechercher des produits",
    cart_title: "Panier",
    cart_close: "Fermer",
    cart_subtotal: "Sous-total",
    cart_save: "Vous économisez",
    cart_total: "Total",
    cart_checkout: "Payer",
    cart_empty: "Panier vide",
    cart_find: "Trouver une offre",
    footer_shop: "Boutique",
    footer_company: "Entreprise",
    footer_legal: "Mentions légales",
    footer_about_company: "À propos de l’entreprise",
    footer_about: "À propos",
    footer_terms: "Conditions d’utilisation",
    footer_privacy: "Confidentialité",
    footer_how: "Comment ça marche",
    footer_all_deals: "Toutes les offres",
    footer_contact: "Contacter le support",
    cta_search: "Ouvrir la recherche",
    cta_browse: "Voir les offres",
    eyebrow_platforms: "Plateformes",
    eyebrow_catalog: "Catalogue",
    view_all: "Tout voir",
    page_deals: "Toutes les offres",
    page_search: "Recherche",
    page_results: "Résultats",
    page_how: "Comment ça marche",
    toast_theme: "Thème mis à jour",
    toast_lang: "Langue mise à jour",
    toast_pay: "Payer en",
    meta_plans: "Offres actives",
    meta_platforms: "Plateformes",
    meta_currencies: "Devises",
    currency_search: "Rechercher une devise (PHP, USD…)",
  },
  de: {
    nav_home: "Start",
    nav_deals: "Angebote",
    nav_search: "Suche",
    nav_mission: "Mission",
    nav_checkout: "Kasse",
    nav_pay: "Zahlen",
    nav_cart: "Warenkorb",
    nav_menu: "Menü",
    nav_prefs: "Einstellungen",
    prefs_title: "Einstellungen",
    prefs_language: "Sprache",
    prefs_theme: "Erscheinungsbild",
    prefs_theme_hint: "Hell, dunkel oder System wählen.",
    prefs_lang_hint: "Sprache für Menüs und Schaltflächen.",
    theme_dark: "Dunkel",
    theme_light: "Hell",
    theme_system: "System",
    search_placeholder: "SuperGrok, Netflix suchen…",
    search_aria: "Produkte suchen",
    cart_title: "Warenkorb",
    cart_close: "Schließen",
    cart_subtotal: "Zwischensumme",
    cart_save: "Sie sparen",
    cart_total: "Gesamt",
    cart_checkout: "Zur Kasse",
    cart_empty: "Warenkorb leer",
    cart_find: "Plan finden",
    footer_shop: "Shop",
    footer_company: "Unternehmen",
    footer_legal: "Rechtliches",
    footer_about_company: "Über das Unternehmen",
    footer_about: "Über uns",
    footer_terms: "Nutzungsbedingungen",
    footer_privacy: "Datenschutz",
    footer_how: "So funktioniert’s",
    footer_all_deals: "Alle Angebote",
    footer_contact: "Support kontaktieren",
    cta_search: "Suche öffnen",
    cta_browse: "Angebote ansehen",
    eyebrow_platforms: "Plattformen",
    eyebrow_catalog: "Katalog",
    view_all: "Alle anzeigen",
    page_deals: "Alle Angebote",
    page_search: "Suche",
    page_results: "Ergebnisse",
    page_how: "So funktioniert’s",
    toast_theme: "Theme aktualisiert",
    toast_lang: "Sprache aktualisiert",
    toast_pay: "Zahlen in",
    meta_plans: "Aktive Pläne",
    meta_platforms: "Plattformen",
    meta_currencies: "Währungen",
    currency_search: "Währung suchen (PHP, USD…)",
  },
  pt: {
    nav_home: "Início",
    nav_deals: "Ofertas",
    nav_search: "Pesquisar",
    nav_mission: "Missão",
    nav_checkout: "Checkout",
    nav_pay: "Pagar",
    nav_cart: "Carrinho",
    nav_menu: "Menu",
    nav_prefs: "Definições",
    prefs_title: "Preferências",
    prefs_language: "Idioma",
    prefs_theme: "Aparência",
    theme_dark: "Escuro",
    theme_light: "Claro",
    theme_system: "Sistema",
    cart_close: "Fechar",
    cart_save: "Poupa",
    cart_total: "Total",
    cart_empty: "Carrinho vazio",
    footer_shop: "Loja",
    footer_company: "Empresa",
    footer_about: "Sobre",
    footer_terms: "Termos de utilização",
    footer_privacy: "Privacidade",
    footer_how: "Como funciona",
    cta_browse: "Ver ofertas",
    view_all: "Ver tudo",
    toast_lang: "Idioma atualizado",
    toast_pay: "Pagar em",
  },
  "pt-BR": {
    nav_home: "Início",
    nav_deals: "Ofertas",
    nav_search: "Buscar",
    nav_mission: "Missão",
    nav_checkout: "Checkout",
    nav_pay: "Pagar",
    nav_cart: "Carrinho",
    nav_menu: "Menu",
    nav_prefs: "Configurações",
    prefs_title: "Preferências",
    prefs_language: "Idioma",
    prefs_theme: "Aparência",
    theme_dark: "Escuro",
    theme_light: "Claro",
    theme_system: "Sistema",
    cart_close: "Fechar",
    cart_save: "Você economiza",
    cart_total: "Total",
    cart_empty: "Carrinho vazio",
    footer_shop: "Loja",
    footer_company: "Empresa",
    footer_about: "Sobre",
    footer_terms: "Termos de uso",
    footer_privacy: "Privacidade",
    footer_how: "Como funciona",
    cta_browse: "Ver ofertas",
    view_all: "Ver tudo",
    toast_lang: "Idioma atualizado",
    toast_pay: "Pagar em",
  },
  ru: {
    nav_home: "Главная",
    nav_deals: "Акции",
    nav_search: "Поиск",
    nav_mission: "Миссия",
    nav_checkout: "Оплата",
    nav_pay: "Оплата",
    nav_cart: "Корзина",
    nav_menu: "Меню",
    nav_prefs: "Настройки",
    prefs_title: "Настройки",
    prefs_language: "Язык",
    prefs_theme: "Оформление",
    theme_dark: "Тёмная",
    theme_light: "Светлая",
    theme_system: "Системная",
    cart_close: "Закрыть",
    cart_save: "Вы экономите",
    cart_total: "Итого",
    cart_empty: "Корзина пуста",
    footer_shop: "Магазин",
    footer_company: "Компания",
    footer_about: "О нас",
    footer_terms: "Условия использования",
    footer_privacy: "Конфиденциальность",
    footer_how: "Как это работает",
    cta_browse: "Смотреть акции",
    view_all: "Смотреть всё",
    toast_lang: "Язык обновлён",
    toast_pay: "Оплата в",
  },
  it: {
    nav_home: "Home",
    nav_deals: "Offerte",
    nav_search: "Cerca",
    nav_mission: "Missione",
    nav_checkout: "Checkout",
    nav_pay: "Paga",
    nav_cart: "Carrello",
    nav_menu: "Menu",
    nav_prefs: "Impostazioni",
    prefs_title: "Preferenze",
    prefs_language: "Lingua",
    prefs_theme: "Aspetto",
    theme_dark: "Scuro",
    theme_light: "Chiaro",
    theme_system: "Sistema",
    cart_close: "Chiudi",
    cart_save: "Risparmi",
    cart_total: "Totale",
    cart_empty: "Carrello vuoto",
    footer_shop: "Negozio",
    footer_company: "Azienda",
    footer_about: "Chi siamo",
    footer_terms: "Termini di utilizzo",
    footer_privacy: "Privacy",
    footer_how: "Come funziona",
    cta_browse: "Vedi offerte",
    view_all: "Vedi tutto",
    toast_lang: "Lingua aggiornata",
    toast_pay: "Paga in",
  },
  nl: {
    nav_home: "Home",
    nav_deals: "Deals",
    nav_search: "Zoeken",
    nav_mission: "Missie",
    nav_checkout: "Afrekenen",
    nav_pay: "Betalen",
    nav_cart: "Winkelwagen",
    nav_prefs: "Instellingen",
    prefs_title: "Voorkeuren",
    prefs_language: "Taal",
    prefs_theme: "Weergave",
    theme_dark: "Donker",
    theme_light: "Licht",
    theme_system: "Systeem",
    cart_close: "Sluiten",
    cart_save: "Je bespaart",
    cart_total: "Totaal",
    cart_empty: "Winkelwagen leeg",
    footer_shop: "Winkel",
    footer_company: "Bedrijf",
    footer_about: "Over",
    footer_terms: "Gebruiksvoorwaarden",
    footer_privacy: "Privacy",
    cta_browse: "Deals bekijken",
    view_all: "Alles bekijken",
    toast_lang: "Taal bijgewerkt",
    toast_pay: "Betalen in",
  },
  tr: {
    nav_home: "Ana sayfa",
    nav_deals: "Fırsatlar",
    nav_search: "Ara",
    nav_mission: "Misyon",
    nav_checkout: "Ödeme",
    nav_pay: "Öde",
    nav_cart: "Sepet",
    nav_prefs: "Ayarlar",
    prefs_title: "Tercihler",
    prefs_language: "Dil",
    prefs_theme: "Görünüm",
    theme_dark: "Koyu",
    theme_light: "Açık",
    theme_system: "Sistem",
    cart_close: "Kapat",
    cart_save: "Tasarruf",
    cart_total: "Toplam",
    cart_empty: "Sepet boş",
    footer_shop: "Mağaza",
    footer_company: "Şirket",
    footer_about: "Hakkında",
    footer_terms: "Kullanım şartları",
    footer_privacy: "Gizlilik",
    cta_browse: "Fırsatları gör",
    view_all: "Tümünü gör",
    toast_lang: "Dil güncellendi",
    toast_pay: "Ödeme birimi",
  },
  pl: {
    nav_home: "Strona główna",
    nav_deals: "Oferty",
    nav_search: "Szukaj",
    nav_mission: "Misja",
    nav_checkout: "Kasa",
    nav_pay: "Zapłać",
    nav_cart: "Koszyk",
    nav_prefs: "Ustawienia",
    prefs_title: "Preferencje",
    prefs_language: "Język",
    prefs_theme: "Wygląd",
    theme_dark: "Ciemny",
    theme_light: "Jasny",
    theme_system: "Systemowy",
    cart_close: "Zamknij",
    cart_save: "Oszczędzasz",
    cart_total: "Suma",
    cart_empty: "Koszyk pusty",
    footer_shop: "Sklep",
    footer_company: "Firma",
    footer_about: "O nas",
    footer_terms: "Regulamin",
    footer_privacy: "Prywatność",
    cta_browse: "Zobacz oferty",
    view_all: "Zobacz wszystko",
    toast_lang: "Zaktualizowano język",
    toast_pay: "Płatność w",
  },
  uk: {
    nav_home: "Головна",
    nav_deals: "Пропозиції",
    nav_search: "Пошук",
    nav_mission: "Місія",
    nav_checkout: "Оплата",
    nav_pay: "Оплата",
    nav_cart: "Кошик",
    nav_prefs: "Налаштування",
    prefs_title: "Параметри",
    prefs_language: "Мова",
    prefs_theme: "Оформлення",
    theme_dark: "Темна",
    theme_light: "Світла",
    cart_close: "Закрити",
    cart_save: "Ви економите",
    cart_total: "Разом",
    cart_empty: "Кошик порожній",
    footer_shop: "Магазин",
    footer_company: "Компанія",
    footer_about: "Про нас",
    footer_terms: "Умови використання",
    footer_privacy: "Конфіденційність",
    cta_browse: "Дивитися пропозиції",
    view_all: "Дивитися все",
    toast_lang: "Мову оновлено",
    toast_pay: "Оплата в",
  },
  ro: {
    nav_home: "Acasă",
    nav_deals: "Oferte",
    nav_search: "Caută",
    nav_mission: "Misiune",
    nav_checkout: "Checkout",
    nav_pay: "Plătește",
    nav_cart: "Coș",
    nav_prefs: "Setări",
    prefs_title: "Preferințe",
    prefs_language: "Limbă",
    prefs_theme: "Aspect",
    theme_dark: "Întunecat",
    theme_light: "Luminos",
    cart_close: "Închide",
    cart_save: "Economisești",
    cart_total: "Total",
    cart_empty: "Coș gol",
    footer_shop: "Magazin",
    footer_company: "Companie",
    footer_about: "Despre",
    footer_terms: "Termeni de utilizare",
    footer_privacy: "Confidențialitate",
    cta_browse: "Vezi oferte",
    view_all: "Vezi tot",
    toast_lang: "Limba a fost actualizată",
    toast_pay: "Plătește în",
  },
  sv: {
    nav_home: "Hem",
    nav_deals: "Erbjudanden",
    nav_search: "Sök",
    nav_mission: "Mission",
    nav_checkout: "Kassa",
    nav_pay: "Betala",
    nav_cart: "Kundvagn",
    nav_prefs: "Inställningar",
    prefs_title: "Inställningar",
    prefs_language: "Språk",
    prefs_theme: "Utseende",
    theme_dark: "Mörkt",
    theme_light: "Ljust",
    theme_system: "System",
    cart_close: "Stäng",
    cart_save: "Du sparar",
    cart_total: "Totalt",
    cart_empty: "Kundvagnen är tom",
    footer_shop: "Butik",
    footer_company: "Företag",
    footer_about: "Om",
    footer_terms: "Användarvillkor",
    footer_privacy: "Integritet",
    cta_browse: "Visa erbjudanden",
    view_all: "Visa alla",
    toast_lang: "Språk uppdaterat",
    toast_pay: "Betala i",
  },
  fi: {
    nav_home: "Etusivu",
    nav_deals: "Tarjoukset",
    nav_search: "Haku",
    nav_mission: "Tehtävä",
    nav_checkout: "Kassa",
    nav_pay: "Maksa",
    nav_cart: "Ostoskori",
    nav_prefs: "Asetukset",
    prefs_title: "Asetukset",
    prefs_language: "Kieli",
    prefs_theme: "Ulkoasu",
    theme_dark: "Tumma",
    theme_light: "Vaalea",
    theme_system: "Järjestelmä",
    cart_close: "Sulje",
    cart_save: "Säästät",
    cart_total: "Yhteensä",
    cart_empty: "Ostoskori on tyhjä",
    footer_shop: "Kauppa",
    footer_company: "Yritys",
    footer_about: "Tietoa",
    footer_terms: "Käyttöehdot",
    footer_privacy: "Tietosuoja",
    cta_browse: "Katso tarjoukset",
    view_all: "Näytä kaikki",
    toast_lang: "Kieli päivitetty",
    toast_pay: "Maksa valuutassa",
  },
  no: {
    nav_home: "Hjem",
    nav_deals: "Tilbud",
    nav_search: "Søk",
    nav_mission: "Misjon",
    nav_checkout: "Kasse",
    nav_pay: "Betal",
    nav_cart: "Handlekurv",
    nav_prefs: "Innstillinger",
    prefs_title: "Preferanser",
    prefs_language: "Språk",
    prefs_theme: "Utseende",
    theme_dark: "Mørk",
    theme_light: "Lys",
    theme_system: "System",
    cart_close: "Lukk",
    cart_save: "Du sparer",
    cart_total: "Totalt",
    cart_empty: "Handlekurven er tom",
    footer_shop: "Butikk",
    footer_company: "Selskap",
    footer_about: "Om",
    footer_terms: "Vilkår",
    footer_privacy: "Personvern",
    cta_browse: "Se tilbud",
    view_all: "Se alle",
    toast_lang: "Språk oppdatert",
    toast_pay: "Betal i",
  },
  da: {
    nav_home: "Hjem",
    nav_deals: "Tilbud",
    nav_search: "Søg",
    nav_mission: "Mission",
    nav_checkout: "Kasse",
    nav_pay: "Betal",
    nav_cart: "Kurv",
    nav_prefs: "Indstillinger",
    prefs_title: "Præferencer",
    prefs_language: "Sprog",
    prefs_theme: "Udseende",
    theme_dark: "Mørk",
    theme_light: "Lys",
    theme_system: "System",
    cart_close: "Luk",
    cart_save: "Du sparer",
    cart_total: "I alt",
    cart_empty: "Kurven er tom",
    footer_shop: "Butik",
    footer_company: "Virksomhed",
    footer_about: "Om",
    footer_terms: "Vilkår",
    footer_privacy: "Privatliv",
    cta_browse: "Se tilbud",
    view_all: "Se alle",
    toast_lang: "Sprog opdateret",
    toast_pay: "Betal i",
  },
  el: {
    nav_home: "Αρχική",
    nav_deals: "Προσφορές",
    nav_search: "Αναζήτηση",
    nav_mission: "Αποστολή",
    nav_checkout: "Ταμείο",
    nav_pay: "Πληρωμή",
    nav_cart: "Καλάθι",
    nav_prefs: "Ρυθμίσεις",
    prefs_title: "Προτιμήσεις",
    prefs_language: "Γλώσσα",
    prefs_theme: "Εμφάνιση",
    theme_dark: "Σκούρο",
    theme_light: "Φωτεινό",
    theme_system: "Σύστημα",
    cart_close: "Κλείσιμο",
    cart_save: "Εξοικονομείτε",
    cart_total: "Σύνολο",
    cart_empty: "Το καλάθι είναι άδειο",
    footer_shop: "Κατάστημα",
    footer_company: "Εταιρεία",
    footer_about: "Σχετικά",
    footer_terms: "Όροι χρήσης",
    footer_privacy: "Απόρρητο",
    cta_browse: "Δείτε προσφορές",
    view_all: "Δείτε όλα",
    toast_lang: "Η γλώσσα ενημερώθηκε",
    toast_pay: "Πληρωμή σε",
  },
  he: {
    nav_home: "בית",
    nav_deals: "מבצעים",
    nav_search: "חיפוש",
    nav_mission: "משימה",
    nav_checkout: "תשלום",
    nav_pay: "שלם",
    nav_cart: "עגלה",
    nav_prefs: "הגדרות",
    prefs_title: "העדפות",
    prefs_language: "שפה",
    prefs_theme: "מראה",
    theme_dark: "כהה",
    theme_light: "בהיר",
    theme_system: "מערכת",
    cart_close: "סגור",
    cart_save: "חיסכון",
    cart_total: "סה״כ",
    cart_empty: "העגלה ריקה",
    footer_shop: "חנות",
    footer_company: "חברה",
    footer_about: "אודות",
    footer_terms: "תנאי שימוש",
    footer_privacy: "פרטיות",
    cta_browse: "צפה במבצעים",
    view_all: "הצג הכל",
    toast_lang: "השפה עודכנה",
    toast_pay: "תשלום ב־",
  },
  bn: {
    nav_home: "হোম",
    nav_deals: "ডিল",
    nav_search: "অনুসন্ধান",
    nav_mission: "মিশন",
    nav_checkout: "চেকআউট",
    nav_pay: "পেমেন্ট",
    nav_cart: "কার্ট",
    nav_prefs: "সেটিংস",
    prefs_title: "পছন্দসমূহ",
    prefs_language: "ভাষা",
    prefs_theme: "থিম",
    theme_dark: "ডার্ক",
    theme_light: "লাইট",
    cart_close: "বন্ধ",
    cart_save: "আপনি সাশ্রয় করছেন",
    cart_total: "মোট",
    cart_empty: "কার্ট খালি",
    footer_shop: "দোকান",
    footer_company: "কোম্পানি",
    footer_about: "সম্পর্কে",
    footer_terms: "ব্যবহারের শর্ত",
    footer_privacy: "গোপনীয়তা",
    cta_browse: "ডিল দেখুন",
    view_all: "সব দেখুন",
    toast_lang: "ভাষা আপডেট হয়েছে",
    toast_pay: "পেমেন্ট মুদ্রা",
  },
  ta: {
    nav_home: "முகப்பு",
    nav_deals: "சலுகைகள்",
    nav_search: "தேடல்",
    nav_mission: "பணி",
    nav_checkout: "செக்அவுட்",
    nav_pay: "செலுத்து",
    nav_cart: "வண்டி",
    nav_prefs: "அமைப்புகள்",
    prefs_title: "விருப்பங்கள்",
    prefs_language: "மொழி",
    prefs_theme: "தோற்றம்",
    theme_dark: "இருள்",
    theme_light: "வெளிச்சம்",
    cart_close: "மூடு",
    cart_save: "நீங்கள் சேமிக்கிறீர்கள்",
    cart_total: "மொத்தம்",
    cart_empty: "வண்டி காலி",
    footer_shop: "கடை",
    footer_company: "நிறுவனம்",
    footer_about: "பற்றி",
    footer_terms: "பயன்பாட்டு விதிமுறைகள்",
    footer_privacy: "தனியுரிமை",
    cta_browse: "சலுகைகளைப் பார்",
    view_all: "அனைத்தையும் பார்",
    toast_lang: "மொழி புதுப்பிக்கப்பட்டது",
    toast_pay: "செலுத்தும் நாணயம்",
  },
  ur: {
    nav_home: "ہوم",
    nav_deals: "ڈیلز",
    nav_search: "تلاش",
    nav_mission: "مشن",
    nav_checkout: "چیک آؤٹ",
    nav_pay: "ادائیگی",
    nav_cart: "کارٹ",
    nav_prefs: "ترتیبات",
    prefs_title: "ترجیحات",
    prefs_language: "زبان",
    prefs_theme: "ظاہری شکل",
    theme_dark: "ڈارک",
    theme_light: "لائٹ",
    cart_close: "بند کریں",
    cart_save: "آپ کی بچت",
    cart_total: "کل",
    cart_empty: "کارٹ خالی ہے",
    footer_shop: "دکان",
    footer_company: "کمپنی",
    footer_about: "تعارف",
    footer_terms: "استعمال کی شرائط",
    footer_privacy: "رازداری",
    cta_browse: "ڈیلز دیکھیں",
    view_all: "سب دیکھیں",
    toast_lang: "زبان اپ ڈیٹ ہو گئی",
    toast_pay: "ادائیگی کی کرنسی",
  },
  fa: {
    nav_home: "خانه",
    nav_deals: "پیشنهادها",
    nav_search: "جستجو",
    nav_mission: "ماموریت",
    nav_checkout: "پرداخت",
    nav_pay: "پرداخت",
    nav_cart: "سبد",
    nav_prefs: "تنظیمات",
    prefs_title: "ترجیحات",
    prefs_language: "زبان",
    prefs_theme: "ظاهر",
    theme_dark: "تیره",
    theme_light: "روشن",
    theme_system: "سیستم",
    cart_close: "بستن",
    cart_save: "صرفه‌جویی شما",
    cart_total: "جمع",
    cart_empty: "سبد خالی است",
    footer_shop: "فروشگاه",
    footer_company: "شرکت",
    footer_about: "درباره",
    footer_terms: "شرایط استفاده",
    footer_privacy: "حریم خصوصی",
    cta_browse: "مشاهده پیشنهادها",
    view_all: "مشاهده همه",
    toast_lang: "زبان به‌روزرسانی شد",
    toast_pay: "پرداخت با",
  },
  sw: {
    nav_home: "Nyumbani",
    nav_deals: "Ofa",
    nav_search: "Tafuta",
    nav_mission: "Dhamira",
    nav_checkout: "Malipo",
    nav_pay: "Lipa",
    nav_cart: "Kikapu",
    nav_prefs: "Mipangilio",
    prefs_title: "Mapendeleo",
    prefs_language: "Lugha",
    prefs_theme: "Muonekano",
    theme_dark: "Giza",
    theme_light: "Mwanga",
    theme_system: "Mfumo",
    cart_close: "Funga",
    cart_save: "Unaokoa",
    cart_total: "Jumla",
    cart_empty: "Kikapu ni tupu",
    footer_shop: "Duka",
    footer_company: "Kampuni",
    footer_about: "Kuhusu",
    footer_terms: "Masharti ya matumizi",
    footer_privacy: "Faragha",
    cta_browse: "Tazama ofa",
    view_all: "Tazama zote",
    toast_lang: "Lugha imesasishwa",
    toast_pay: "Lipa kwa",
  },
};

function packFor(lang) {
  const o = OVERRIDES[lang];
  return o ? { ...EN, ...o } : EN;
}

export function getThemePref() {
  try {
    const v = localStorage.getItem(THEME_KEY);
    if (v === "light" || v === "dark" || v === "system") return v;
  } catch {
    /* ignore */
  }
  return "dark";
}

export function getLang() {
  try {
    const v = localStorage.getItem(LANG_KEY);
    if (v && LANG_IDS.has(v)) return v;
  } catch {
    /* ignore */
  }
  return "en";
}

export function getLangMeta(lang = getLang()) {
  return LANGUAGES.find((l) => l.id === lang) || LANGUAGES[0];
}

export function resolveTheme(pref = getThemePref()) {
  if (pref === "system") {
    try {
      return window.matchMedia("(prefers-color-scheme: light)").matches
        ? "light"
        : "dark";
    } catch {
      return "dark";
    }
  }
  return pref === "light" ? "light" : "dark";
}

export function applyTheme(pref = getThemePref()) {
  const resolved = resolveTheme(pref);
  document.documentElement.setAttribute("data-theme", resolved);
  document.documentElement.setAttribute("data-theme-pref", pref);
  const meta = document.querySelector('meta[name="theme-color"]');
  if (meta) meta.setAttribute("content", resolved === "light" ? "#f4f4f5" : "#000000");
  document.querySelectorAll("img.logo-mark").forEach((img) => {
    img.style.background = resolved === "light" ? "#fff" : "#000";
  });
  return resolved;
}

export function applyLang(lang = getLang()) {
  const code = LANG_IDS.has(lang) ? lang : "en";
  const meta = getLangMeta(code);
  const htmlLang = code === "zh" ? "zh-CN" : code;
  document.documentElement.lang = htmlLang;
  document.documentElement.setAttribute("data-lang", code);
  document.documentElement.dir = meta.dir || "ltr";
  return code;
}

export function setThemePref(pref) {
  const v = pref === "light" || pref === "system" ? pref : "dark";
  try {
    localStorage.setItem(THEME_KEY, v);
  } catch {
    /* ignore */
  }
  applyTheme(v);
  window.dispatchEvent(new CustomEvent("prefs:theme", { detail: v }));
  return v;
}

export function setLang(lang) {
  const v = LANG_IDS.has(lang) ? lang : "en";
  try {
    localStorage.setItem(LANG_KEY, v);
  } catch {
    /* ignore */
  }
  applyLang(v);
  window.dispatchEvent(new CustomEvent("prefs:lang", { detail: v }));
  return v;
}

/** Admin-editable English UI overrides (settings.uiStrings). Safe no-op if unused. */
let adminUiOverrides = {};

export function setAdminUiOverrides(obj) {
  adminUiOverrides =
    obj && typeof obj === "object" && !Array.isArray(obj) ? { ...obj } : {};
}

export function getAdminUiOverrides() {
  return { ...adminUiOverrides };
}

export function getDefaultUiStrings() {
  return { ...EN };
}

export function t(key, lang = getLang()) {
  if (lang === "en" && adminUiOverrides[key] != null && String(adminUiOverrides[key]).length) {
    return String(adminUiOverrides[key]);
  }
  const pack = packFor(lang);
  if (pack[key]) return pack[key];
  if (adminUiOverrides[key] != null && String(adminUiOverrides[key]).length) {
    return String(adminUiOverrides[key]);
  }
  return EN[key] || key;
}

export function fillLanguageSelect(selectEl) {
  if (!selectEl) return;
  const current = getLang();
  selectEl.innerHTML = LANGUAGES.map(
    (l) =>
      `<option value="${l.id}"${l.id === current ? " selected" : ""}>${escapeOpt(
        l.native
      )} — ${escapeOpt(l.label)}</option>`
  ).join("");
  selectEl.value = current;
}

function escapeOpt(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function initPrefs() {
  applyTheme(getThemePref());
  applyLang(getLang());
  try {
    window
      .matchMedia("(prefers-color-scheme: light)")
      .addEventListener("change", () => {
        if (getThemePref() === "system") applyTheme("system");
      });
  } catch {
    /* ignore */
  }
}
